CREATE TABLE Authors (
  ID SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE Books (
  ID SERIAL PRIMARY KEY NOT NULL,
  ISBN DECIMAL(13, 0) NOT NULL,
  title VARCHAR(100) NOT NULL,
  cover VARCHAR(400)
);

CREATE TABLE Books_Authors (
  ID SERIAL PRIMARY KEY NOT NULL,
  books_id INT NOT NULL REFERENCES Books(ID),
  authors_id INT NOT NULL REFERENCES Authors(ID),
  num INT NOT NULL,

  UNIQUE (books_id, authors_id)
);